# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://bereket6725.github.io/
baseurl: /
title: Bereket Ghebremedhin
author: Bereket Ghebremedhin
description: Personal site and resume
avatar: profile.png
email: bereket6725@gmail.com
github: bereket6725
twitter: bereketg1992
linkedin: bereket-ghebremedhin-49988050
# stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
# disqus: username
# google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
